= Упражнения

. Доработайте распознаватель, созданный с помощью https://github.com/mohamed/fsm2sv[fsm2sv], так, чтобы он поддерживал числа от 1 до 8.
+
TIP: Для подключения дополнительных светодиодов используйте FloorPlanner.
+
NOTE: Для Mega 138k необходимо использовать модуль PMOD_LEDx8.

. Изучите инструменты и отчёты Gowin EDA.
Инструменты можно найти в разделе "Tools" на верхней панели.
Отчёты, доступные для проекта, можно изменив вид левой панели с "Design", в котором отображаются файлы проекта, на "Process".
Ответьте на следующие вопросы.

.. На сколько увеличилось потребление ресурсов при расширении поддержки диодов с 6 до 8? Потребление каких типов ресурсов выросло? Почему? Потребление каких ресурсов осталось неизменным?
.. Какова частота, на которой сможет работать платка с разработанной логикой? Изменилась ли она при переходе от 6 диодов к 8?
.. Сколько LUT-ячеек требуется для реализации автомата, управляющего диодами?

. Реализуйте модуль-счётчик.
При нажатии на кнопку число на семисегментном индикаторе должно увеличиваться.

.. В нашем распоряжении есть модуль с двумя семисегментными индикаторами (PMOD_DTx2).
По умолчанию горит только правый индикатор, чтобы переключиться на левый, нужно подать сигнал на пин "SEL".
Подумайте как можно сделать так, чтобы можно было выводить двузначные числа.
Как можно выводить числа от 0 до 255?
.. Кнопок у нас больше чем одна, попробуйте реализовать другие арифметические операции.

////

. Реализуйте обнаружение границ объекта в реальном времени.
Задача сложная, поэтому предполагается решать её поэтапно.
.. Изучите примеры `rgb_screen` (проще, использует дисплей на плате, **только для Mega 138k**) или `hdmi_colorbar_1080` (сложнее, используется HDMI выход) из репозитория с примерами для https://github.com/sipeed/TangMega-138KPro-example/tree/main[Mega 138k].
.. Модифицируйте их для вывода изображения по вашему выбору.
.. Подключите камеру OV7670 и настройте вывод на дисплей.
Вам может помочь https://habr.com/ru/articles/283488/[данная статья].
.. Примените ваш модуль свёртки для обработки изображения с камеры.
.. Научитесь менять ядро свёртки, например, по нажатию кнопки.
.. Постройте цепочку свёрток, управляемую с помощью DIP переключателей.
Для обнаружения границ потребуются как минимум размытие и сама детекция.

. Работа со звуком??? (**Только для Mega 138k**, см. https://github.com/sipeed/TangMega-138KPro-example/tree/main/audio, https://www.fpga4fun.com/MusicBox.html, I2S)
////
