= Упражнения

. Доработайте распознаватель, созданный с помощью https://github.com/mohamed/fsm2sv/tree/mai[fsm2sv], так, чтобы он поддерживал числа от 1 до 8.
+
TIP: Для подключения дополнительных светодиодов используйте FloorPlanner.
+
NOTE: Для Mega 138k необходимо использовать модуль PMOD_LEDx8.

. Изучите инструменты и отчёты Gowin EDA.
Инструменты можно найти в разделе "Tools" на верхней панели.
Отчёты, доступные для проекта, можно изменив вид левой панели с "Design", в котором отображаются файлы проекта, на "Process".
Ответьте на следующие вопросы.

.. На сколько увеличилось потребление ресурсов при расширении поддержки диодов с 6 до 8? Потребление каких типов ресурсов выросло? Почему? Потребление каких ресурсов осталось неизменным?
.. Какова частота, на которой сможет работать платка с разработанной логикой? Изменилась ли она при переходе от 6 диодов к 8?
.. Сколько LUT-ячеек требуется для реализации автомата, управляющего диодами?


////
. Реализуйте счётчик.
Для ввода можно использовать как одну так и несколько кнопок, чтобы достичь большего шага.
Для вывода используйте модуль с семисегментный индикаторами (PMOD_DTx2).
+
TIP: Подумайте как вывести числа больше 99.
+
TIP: Не забывайте о том, что наши глаза не замечают мерцания высокой частоты.

. Работа со звуком??? (**Только для Mega 138k**, см. https://github.com/sipeed/TangMega-138KPro-example/tree/main/audio, https://www.fpga4fun.com/MusicBox.html, I2S)
////
