= 4. Мультиплексоры и демультиплексоры

Мультиплексирование (multiplexing) — важный дизайн-петтерн, идея которого заключается в объединении аналоговых или цифровых сигналов в один канал.
На принимающей же стороне эти сигналы разделяются, это называется демультиплексирование (demultiplexing).
В цифровой логике же этот дизайн паттерн реализуется через комбинационные схемы особого вида мультиплексоры (MUX) и демультиплексоры (DEMUX) соответственно и используются, например.

1. Для реализации логических функций и, связанное с этим, реализации LUT-ов.
2. Для маршрутизации данных.
3. Для декодирования адресов.

== Мультиплексор

Мультиплексор — это устройство, которое выбирает один из нескольких входных сигналов и передаёт его на выход в зависимости от значения управляющих сигналов (селекторов). Простейший пример — 2:1 MUX, который имеет два входа, один выход и один управляющий сигнал.

В простейшем случае это просто тернарный оператор.
[source, verilog]
.src/04-mux-demux/mux_2to1.sv
----
include::example$mux_2to1.sv[]
----

Схема такого мультиплексора выглядит довольно просто.

image::mux_2to1.svg[title="Схема мультиплексора 2:1"]

И она тоже реализуется при помощи привычных логических операторов.

image::mux_2to1_logic.svg[title="Схема мультиплексора 2:1 через логические элементы"]

Мультиплексоры больших порядков можно реализовать как через логические операторы, так и через мультиплексоры меньшей разрядности.
Например, 4:1 MUX выглядит так.
[source, verilog]
.src/04-mux-demux/mux_4to1.sv
----
include::example$mux_4to1.sv[]
----
<1> Промежуточные провода.
<2> Выбор по старшему биту.
<3> Передача промежуточных выборов.
<4> Выбор по младшему биту.


Со следующей схемой.

image::mux_4to1.svg[title="Схема мультиплексора 4:1 через мультиплексоры 2:1"]

== Демультиплексор

Демультиплексор выполняет обратную функцию: он направляет один входной сигнал на один из нескольких выходов в зависимости от управляющих сигналов. Простейший пример — 1:2 демультиплексор.

image::demux_1to2.svg[title="Схема демультиплексора 1:2"]

В сочетании с мультиплексором, позволяет использовать один ресурс нескольким сигналам.

== Связь с LUT

LUT (Look-Up Table) — это таблица истинности, которая хранит результат для всех возможных комбинаций входных сигналов.
В ПЛИС LUT реализуются с помощью мультиплексоров и является одним из важнейший её ресурсов: большая части логики работает именно на LUT-ах{empty}footnote:[https://marsohod.org/projects/plata1/166-minicpld].
Например, LUT с двумя входами может быть представлен как 4:1 MUX: два бита селекторов отвечает за вход, а входы мультиплексора будут значениями на соответствующем входе.

Реализуем для примера импликацию через LUT.

[source, verilog]
.src/04-mux-demux/lut_imply.sv
----
include::example$lut_imply.sv[]
----

По сути мы просто записали таблицу истинности для импликации.
|===
| a (`sel[0]`) | b (`sel[1]`) | c (`out`)

| 0 | 0 | 1 (`in[0]`)
| 0 | 1 | 1 (`in[1]`)
| 1 | 0 | 0 (`in[2]`)
| 1 | 1 | 1 (`in[3]`)
|===

IMPORTANT: Обязательно порешайте xref:exercises.adoc[упражнения].
