= 4?. Мультиплексоры и демультиплексоры

Мультиплексоры (MUX) и демультиплексоры (DEMUX) — это важные комбинационные схемы, широко используемые в цифровой логике, например.

1. Для реализации логических функций и, связанное с этим, реализации LUT-ов.
2. Для маршрутизации данных.
3. Для декодирования адресов.

== Мультиплексор

Мультиплексор — это устройство, которое выбирает один из нескольких входных сигналов и передаёт его на выход в зависимости от значения управляющих сигналов (селекторов). Простейший пример — 2:1 MUX, который имеет два входа, один выход и один управляющий сигнал.

В простейшем случае это просто тернарный оператор.
[source, verilog]
.src/xx-mux-demux/mux_2to1.sv
----
include::example$mux_2to1.sv[]
----

Схема такого мультиплексора выглядит довольно просто.

image::mux_2to1.svg[title="Схема мультиплексора 2:1"]

И она тоже реализуется при помощи привычных логических операторов.

image::mux_2to1_logic.svg[title="Схема мультиплексора 2:1 через логические элементы"]

Мультиплексоры больших порядков можно реализовать как через логические операторы, так и через мультиплексоры меньшей разрядности.
Например, 4:1 MUX выглядит так.
[source, verilog]
.src/xx_mux_demux/mux_4to1.sv
----
include::example$mux_4to1.sv[]
----
<1> Промежуточные провода.
<2> Выбор по младшему биту.
<3> Передача промежуточных выборов.
<4> Выбор по старшему биту.


Со следующей схемой.

image::mux_4to1.svg[title="Схема мультиплексора 4:1 через мультиплексоры 2:1"]

== Демультиплексор

Демультиплексор выполняет обратную функцию: он направляет один входной сигнал на один из нескольких выходов в зависимости от управляющих сигналов. Простейший пример — 1:2 демультиплексор.

image::demux_1to2.svg[title="Схема демультиплексора 1:2"]

В сочетании с мультиплексором, позволяет использовать один ресурс нескольким сигналам.

=== Связь с LUT

LUT (Look-Up Table) — это таблица истинности, которая хранит результат для всех возможных комбинаций входных сигналов.
В ПЛИС LUT реализуются с помощью мультиплексоров и является одним из важнейший её ресурсов: большая части логики работает именно на LUT-ах{empty}footnote:[сюда бы какой-то источник нестыдный, не уверен, что https://fpgainsights.com/fpga/overview-of-lookup-tables-lut-in-fpga-design/[такое] подойдёт].
Например, LUT с двумя входами может быть представлен как 4:1 MUX: два бита селекторов отвечает за вход, а входы мультиплексора будут значениями на соответствующем входе.


IMPORTANT: Обязательно порешайте xref:exercises.adoc[упражнения].
