= Упражнения

Продолжим работу со свёрткой изображений.

. Добавьте блоки памяти в режиме "только чтение", в которых будут храниться веса ядер. Предусмотрите возможность использовать одни и те же веса для инициализации нескольких ядер.
  Создайте примеры файлов для инициализации: веса для размытия по Гауссу (5х5) и для выделения границ (5х5).
. Сконфигурируйте буфер для хранения одного изображения. Придётся предположить, что работаем с изображениями ограниченного сверху размера. Скажем, 640 на 480. Используйте его для сохранения результатов свёртки.
. Реализуйте буфер для применения свёртки: `k+1` (где `k` -- размер ядра) лайн буфер, один "перещёлкивается", когда нужно обработать следующую строку изображения.
. Сохраните полученный буфер в DDR3.

Отдельно, в качестве задачи со звёздочкой предлагается запустить свёртку на реальной плате.
Более того, предлагается реализовать выделение границ объекта в реальном времени.
Задача сложная, поэтому предполагается решать её поэтапно.

. Изучите примеры `rgb_screen` (проще, использует дисплей на плате, **только для Mega 138k**) или `hdmi_colorbar_1080` (сложнее, используется HDMI выход) из репозитория с примерами для https://github.com/sipeed/TangMega-138KPro-example/tree/main[Mega 138k].
. Модифицируйте их для вывода изображения по вашему выбору.
. Подключите камеру OV7670 и настройте вывод на дисплей.
Вам может помочь https://habr.com/ru/articles/283488/[данная статья] и примеры кода: https://github.com/amsacks/OV7670-camera[пример раз] и https://github.com/westonb/OV7670-Verilog[пример два].
. Реализуйте модуль преобразования входного изображения в чёрно-белое (градации серого, 8 бит).
. Примените один модуль свёртки (скажем, обнаружение границ) для обработки изображения с камеры. Для этого придётся реализовать модуль, управляющий буферами строк.
. Соберите последовательность свёрток.
.. Два последовательных размытия (с одинаковыми весами).
.. Обнаружение границ.
.. Обратите внимание на то, что размер изображения на выходе может не совпадать с размером изображения на входе.
. Сделайте последовательность свёрток конфигурируемой.
.. Каждую из свёрток можно независимо включить или отключить.
.. Для управления можно использовать DIP переключатели.
.. Предусмотрите возможность подключения диагностических диодов, которые бы показывали, какие модули активны.
.. Обратите внимание на то, что размер изображения на выходе может не совпадать с размером изображения на входе. При этом, то, на сколько будет не совпадать, зависит от количества ядер.

Отдельно, в качестве продолжения работы с PCIe, предлагается передать изображение с хоста на устройство и выполнить свёртку. Предлагаем следующие шаги решения.

. Добавьте DDR3-контроллер к реализованному ранее PCIe-проекту. Поскольку на общей AXI-шине теперь работает несколько master-устройств (PCIe SGDMA-контроллер и AXI DMA-контроллер DDR3), для их подключения потребуется https://github.com/alexforencich/verilog-axi/blob/master/rtl/axi_interconnect.v[AXI Interconnect] (и еще один AXI DMA).
. Модифицируйте хост-программу и модуль управления `BAR2` так, чтобы можно было передавать адрес и размер изображения, которое требуется обработать, а также запускать свёртку.
. Примените один из ранее реализованных модулей свёртки (например, обнаружение границ) для обработки загруженного изображения.
. Сохраните результат свёртки в DDR3.
. Прочитайте с хоста полученные данные и сравните их с ожидаемым результатом.
