= Формальная верификация

В отличие от комбинационных схем, где выход зависит исключительно от текущих входов, последовательностная логика оперирует состояниями. Это вносит следующие изменения в подход к верификации:

. Чтобы проверять секвенциальную логику, необходимо сопоставлять текущие значения сигналов с их значениями в прошлом. Для этого используются системные функции:

* `$past(сигнал)` возвращает значение сигнала на 1 такт назад.
* `$stable(сигнал)` эквивалентен проверке `сигнал == $past(сигнал)`.
* `$rose(сигнал)`/`$fell(сигнал)` фиксируют переход сигнала в логическую единицу или ноль относительно предыдущего такта.

. Солвер пытается найти уязвимость, инициализировав регистры *любыми* возможными значениями. Без явных ограничений начального состояния проверка может стартовать с недостижимых в реальности конфигураций. Для самых простых случаев достаточно явно указать значения внутренних триггеров равными `0` (что обычно мы подразумеваем при проектировании). В иных случаях, можно анализировать только те, случаи, которые следуют после деактивации сигнала сброса `rst`.

NOTE: Обратите внимание, что ограничения `assume` накладываются на все проверяемые свойства `assert`.

. Если для комбинационной логики достаточно проверки на глубину в 1 такт, то для последовательностных схем требуется индивидуальный подбор параметра `depth`. Избыточная глубина увеличивает время работы солвера, а недостаточная — не позволяет покрыть целевые сценарии.

Разберём верификацию уже известного нам модуля `sum_reduce`:

[source, verilog]
.src/06-sequential-logic/formal-verification/sum_reduce_fv.sv
----
include::example$sum_reduce_fv.sv[]
----
<1> Поскольку в самый первый такт работы схемы у сигналов ещё нет информации о прошлом состоянии, то оператор `$past()` вернёт неопределённое значение. Данный флаг позволяет нам пропустить данное состояние при верификации.
<2> Принудительно заставляем начинать анализ из состояния сброса (`rst`) (например, чтобы избежать значения `acc` не равным `0` на первом такте).
<3> Проверка, что если на предыдущем такте был активен сигнал `rst`, то на текущем такте внутренний `acc` должен обнулиться, а выход `sum` — принять текущее значение `num`.
<4> Поиск цепочки сигналов, при которой в отсутствие сброса текущая сумма корректно складывается из предыдущей суммы и нового входного значения `num`.
<5> Проверка переполнения при достижении максимального значения (`MAX_VAL`).

Запустив SymbiYosys в режиме `bmc` с `depth 20`, получим ожидаемый результат `PASS`. Теперь посмотрим на трассу, сгенерированную в режиме `cover`:

[source, smtc]
----
include::example$trace0.smtc[]
----
<1> Начальное состояние регистров, выбранное SMT-солвером для выполнения условий `cover`. Yosys на этапе подготовки создал необходимые переменные для работы. Нам интересны регистры `acc` и `past_valid`, которым присвоены значения `0`, `false` (это ожидаемые нами значения, но так солвер подбирает не всегда).
<2> Первый такт: солвер устанавливает сигнал `rst` в `true` для выполнения условий ограничений.
<3> Второй такт: сигнал сброса деактивируется, но `$past(rst) = 1`. `num = 0`, `acc = 0` => `sum = 0`.
<4> Третий такт: `$past(rst)` теперь равен `0`. `num = 1`, `acc = 0` => `sum = 1`, то есть выражение в `cover` истинно. Но как и с триггерами, результат будет зафиксирован на следующем фронте клока{empty}footnote:[https://symbiyosys.readthedocs.io/en/latest/verilog.html#systemverilog-immediate-assertions].

IMPORTANT: Не забывайте про xref:exercises.adoc[упражнения].
