= 7. Автоматы

В общем виде автомат можно понимать как систему, которая может находиться в каком-то из заранее известного множества состояний, переходить из одного состояния в другое под определённым внешним воздействием.


== Конечный автомат

Конечные автоматы возникают и изучаются в различных областях науки.
Традиционно, в теории формальных языков.
Туда и рекомендуется заглянуть для более фундаментального ознакомления с темой.
В частности, можно обратиться к следующей литературе.

* Классика по теории формальных языков: https://dl.acm.org/doi/book/10.5555/578595[M. A. Harrison. 1978. "Introduction to Formal Language Theory"].
* Свежее по теории автоматов и их применению в различных областях: https://ems.press/books/standalone/172[Editors: Jean-Éric Pin. 2021. "Handbook of Automata Theory"].

Нас же будут интересовать детерминированные конечные автоматы.

====
Детерминированный конечный автомат -- это кортеж
stem:[\langle \Sigma, Q,q_s, Q_f, \delta \rangle],
где

* stem:[\Sigma]
* stem:[Q]
* stem:[q_s]
* stem:[Q_f]
* stem:[\delta]

====



== Автомат Мили

Выходная лента, вывод на переход

== Автомат Мура

Выходная лента, вывод в состоянии.

== Автоматы в HDL

Генерация.

* https://www.mathworks.com/help/hdlcoder/ug/using-mealy-and-moore-machine-types-in-hdl-code-generation.html
* https://docs.amd.com/v/u/2018.3-English/ug901-vivado-synthesis
* https://github.com/mohamed/fsm2sv/tree/main


IMPORTANT: Обязательно порешайте xref:exercises.adoc[упражнения].
