= Упражнения

. Перепишите самые интересные тестбенчи из тех, что мы (или вы) написали ранее.
Тут тоже затесалось https://docs.cocotb.org/en/stable/library_reference.html#cocotb.regression.TestFactory[метапрограммирование].
Несложное, но может быть очень удобным.
. Напишите (или перепишите, если уже сделали на SystemVerilog) тесты к xref:05-bus:exercises.adoc[последним упражнениям] на cocotb. Интереснее всего 3 и 4 задания.
. Реализуйте операцию xref:Appendix-ImageConvolution:index.adoc[свёртки изображения] на SystemVerilog.
    * Предлагается для начала реализовать модуль, который делает одномерную свёртку, затем научиться собирать из него модуль, который получает на выходе одну строку нового изображения.
    * Интерфейс разрабатываемого модуля должен предусматривать загрузку весов ядра свёртки.
    * Модуль должен быть параметризуем размером ядра. Предполагаем, что ядро квадратное, нечётного размера.
    * На входе k строк входного изображения, на выходе одна строка нового изображения.
    * Заранее определитесь, каким образом будут обрабатываться пиксели на краях.
    * Реализуйте тесты для разработанного модуля с использованием cocotb.
