= 6. Инструменты для тестирования

Как мы увидели в xref:05-bus:index.adoc[прошлый раз] мы увидели, что писать тестбенчи на SystemVerilog не очень приятно.
Конечно, уже существуют решения для облегчения этой задачи.
Одно из них -- библиотека https://github.com/cocotb/cocotb/tree/master[cocotb], её мы и рассмотрим подробнее.
Для начала, нам нужно её установить.
Можно посмотреть, как это сделать xref:installation.adoc[здесь].

Для начала посмотрим на простейший пример.

[, python]
.src/06-cocotb/adder_1_bit/adder_1_bit_tb.py
----
include::example$adder_1_bit_tb.py[]
----
<1> Если мы хотим указать, что это тестирующая функция, то надо использовать такой декоратор{empty}footnote:[https://docs.cocotb.org/en/stable/library_reference.html#cocotb.test].
<2> Заметим, что функция асинхронная. Надо к этому привыкать, весь интсрумент сильно завязан на этом.
`dut` -- знакомое нам название, тут оно тоже означает объект, который мы тестируем.
<3> Задаём входные параметры. Здесь можно писать просто числа, но иногда нужно делать что-то более хитрое{empty}footnote:[https://docs.cocotb.org/en/stable/library_reference.html#hdl-datatypes].
<4> Кладём значения в переменные модуля.
<5> Задаём задержку в 1 наносекунду.
<6> Проверяем какое-то условие, концепция `assert` нам уже знакома.

Для того, чтобы запустить тест можно написать Makefile (есть альтернатива, которую мы пока рассматривать не будем).
[, make]
src/06-cocotb/adder_1_bit/Makefile
----
include::example$Makefile_adder[]
----
Подробнее о том, что значит каждый элемент можно посмотреть в https://docs.cocotb.org/en/stable/quickstart.html#creating-a-makefile[документации].

Теперь можно рассмотреть более сложный пример.
[, python]
.src/06-cocotb/bus/bus_test.py
----
include::example$bus_test.py[]
----
