= Свёртка
:xrefstyle: short

Свёртка двух функций stem:[f] и stem:[g] в дискретном случае определяется следующим образом:

[stem]
++++
  (f*g)(n)=\sum _{m=-\infty }^{\infty }f(m)g(n-m)
++++

На практике часто используются так называемые одномерная и двумерная свёртки для цифровой обработки сигналов (в частности, изображений).

== Одномерная свёртка

Одномерная свёртка часто используется для цифровой обработки сигналов.
Например, https://www.algorithm-archive.org/contents/convolutions/1d/1d.html[здесь] проводится достаточно подробный разбор одномерной свёртки в таком контексте с примерами и визуализацией.
Мы будем использовать её как подготовку и составную часть для свёртки изображений.

== Свёртка изображений

Другие названия: image filtering, image convolution. Да-да, ровно то, что применяется в свёрточных нейронных сетях.

В рамках нашего курса считаем, что работаем с чёрно-белым изображением: байт на пиксель, без альфа-каналов и прочих деталей.
То есть изображение может быть представлено как двумерная матрица байт (прозрачности нет, метаданных нет).

Ядро свёртки -- квадратная матрица нечётного, как правило небольшого, размера.

Пусть есть изображение stem:[A] произвольного размера и ядро свёртки stem:[B] размера stem:[m \times m].
Пусть stem:[p = \lfloor m / 2 \rfloor].

Тогда свёртка изображения stem:[A] ядром stem:[B] -- это изображение (также матрица) stem:[C], такая что.

[stem]
++++
    C[i,j] = \sum_{k=-p}^{p} \sum_{l=-p}^{p} A[i-k,j-l]B[p+k,p+l]
++++

IMPORTANT: Обратите внимание на то, что формула выше не учитывает обработку пикселей на краю изображения, которая может быть организована разными способами.

IMPORTANT: Обратите внимание на то, фильтр можно представить как матрицу (часто чисел с плавающей точкой), а можно и как целочисленную матрицу и коэффициент перед ней.

NOTE: Подумайте, как соотносится данная формула с общим определением свёртки, данным в начале раздела.

Если пиксель на краю, то возможно несколько вариантов.

 * Использовать дефолтное значение
 * Копировать край
 * Применять свёртку так, чтобы не было выхода за границу. Тогда размер выходного изображения будет меньше входного.

В нейронных сетях веса в матрице stem:[B] как раз таки "обучаются".
Но существуют предопределённые ядра, выполняющие вполне конкретные операции: размытие, выделение границ.
Больше примеров:

 * https://sbme-tutorials.github.io/2018/cv/notes/4_week4.html[Image Filtering and Edge Detection]
 * https://lodev.org/cgtutor/filtering.html[Image Filtering]

== Выражение двумерной свёртки через одномерную

В нашем курсе мы декомпозируем двумерную свёртку в набор одномерных следующим образом.
Пусть ядро двумерной свёртки stem:[B] имеет размер stem:[m \times m].
Тогда для вычисления одной строки нового ("свёрнутого") изображения нужно обработать stem:[m] строк исходного изображения stem:[A].
Пусть это буду строки stem:[k \ldots k + m - 1].
Тогда на первом шаге необходимо применить одномерную свёртку к каждой строке изображения и соответствующей строке ядра:
stem:[A[k\]] и stem:[B[0\]], stem:[A[k+1\]] и stem:[B[1\]] и так далее. После чего поэлементно сложить результаты этих свёрток.

<<img_convolution_scheme>> показывает общую, без детализации, схему итогового решения.

[#img_convolution_scheme]
image::convolution_scheme.svg[title="Схема предлагаемой реализации свёртки"]

Заметим, что данное решение не претендует на оптимальность и организовано представленным образом исключительно в целях упрощения обучения.

. Предполагаем, что изображение (например, с камеры) поступает последовательно по строкам.
. Первое, что сделаем (чтобы упростить себе дальнейшую жизнь) -- преобразуем потенциально цветное изображение в градации серого.
. Далее, для успешного применения фильтра, нам надо накопить stem:[m] строк. Для этого выделим буфера в памяти (LineBuffers).
Их будет stem:[m+1] для того, чтобы параллельно с обработкой уже накопленных stem:[m] записывать следующую строку не боясь перетереть данные.
Коммутатор (stem:[1\text{-to-}(m+1)]) как раз будет управлять тем, в какой буфер нужно записывать данные.
. По мере готовности через второй коммутатор (stem:[(m+1)\text{-to-}m]) будут выбираться stem:[m] последовательных строк для обработки.
. К каждой строке применяется одномерная свёртка с соответствующей частью двумерного ядра.
. После чего производится суммирование (модуль Sum).
. Результат накапливается в буфере очередного кадра (FrameBuffer).

Пошаговой реализации такого решения будут посвящены упражнения в курсе (с некоторыми дополнениями и ответвлениями для изучения важных тем и отработки навыков).


IMPORTANT: Обязательно порешайте xref:exercises.adoc[упражнения].
