= Установка Gowin EDA

Для ПЛИС, доступных программе курса, требуется полноценная версия Gowin EDA, скачать которую можно https://www.gowinsemi.com/en/support/download_eda/[здесь] (требуется регистрация для просмотра страницы, но не скачивания).
Для этой версии требуется лицензия, которую кажется можно получить бесплатно, но вместо этого можно использовать сервер лицензий от Sipeed.
Актуальный IP адрес стоит искать https://wiki.sipeed.com/hardware/en/tang/Tang-Nano-Doc/install-the-ide.html#About-the-license[здесь] или https://wiki.sipeed.com/hardware/en/tang/tang-mega-138k/mega-138k-pro.html#Getting-Started[здесь].

Далее для установки стоит выполнить следующие действия.
[, console]
----
$ cd $FPGA_TOOLS/repos
$ wget https://cdn.gowinsemi.com.cn/Gowin_V1.9.12.02_SP2_linux.tar.gz
$ tar -xf Gowin_V1.9.12.02_SP2_linux.tar.gz
$ cp -rf IDE/* $FPGA_TOOLS
$ rm -rf IDE
----

Теперь инструменты от Gowin будут в `PATH`

[TIP]
====
Мы скачиваем версию `1.9.12_SP2`, но со временем она может устареть.
Поэтому если возникает ошибка, то имеет смысл попробовать более новые версии.
За обновлениями можно следить https://www.gowinsemi.com/en/support/database/14/[здесь].
====

[CAUTION]
====
Под Arch Linux инструменты от Gowin не могут найти некоторые библиотеки, поэтому запускать приложения надо указывая им пути к библиотекам с помощью `LD_PRELOAD`.
Например, так:
[, console]
----
$ LD_PRELOAD="/usr/lib/libfreetype.so:/usr/lib/libpng16.so:/usr/lib/libz.so" gw_ide
----
====

Остается активировать САПР, для этого стоит запустить графический интерфейс:
[,console]
----
$ gw_ide
----
Подождать, нажать "ОК", откроется мастер лицензий, куда стоит ввести IP адрес сервера лицензий, проверить, что подключение успешно, нажав кнопку "Check", и сохранить настройки кнопкой "Check".
