= Формальная верификация

В прошлых модулях мы xref:testbench_ci.adoc[познакомились] с классическими тестбенчами. Однако для комбинационной логики есть способ, который позволяет добиться большего уровня уверенности за более короткое время.

Формальная верификация использует математический подход для проверки корректности аппаратуры. Инструменты преобразуют код на языке описания аппаратуры в систему логических уравнений и доказывают выполнение заданных свойств для всех возможных входных конфигураций.

NOTE: «В формальной верификации нет ничего нового: коммерческие инструменты существуют уже несколько десятилетий. Но простой в использовании альтернативы с открытым исходным кодом, которая могла бы загружать проект на языке Verilog с заданными формальными ограничениями, не было. Так было до выхода SymbiYosys.»{empty}footnote:[https://tomverbeure.github.io/rtl/2019/01/04/Under-the-Hood-of-Formal-Verification.html]

== Инструменты и определения

https://github.com/YosysHQ/sby[SymbiYosys (SBY)] -- фронтенд автоматизации верификации. Парсит конфигурационные файлы (`.sby`), управляет запуском Yosys и передает сформированные уравнения вычислительным движкам (SMT/SAT-солверам). Yosys в свою очередь транслирует код Verilog/SystemVerilog во внутреннее представление, преобразуя логику в математические форматы.

В основе анализа лежит задача выполняемости булевых формул (SAT, Satisfiability). Это математическая задача определения того, существует ли такой набор значений для логических переменных, при котором вся заданная булева формула принимает значение 1.

В контексте верификации эта задача формулируется «от противного». Формальный инструмент составляет уравнение для проверяемого условия, а SAT-солвер пытается найти такой набор входных значений, при котором это выражение станет истинным. Если найдена комбинация входов, нарушающая условия, солвер останавливает анализ и генерирует контрпример -- файл трассы (trace), который можно открыть в GTKWave.

SMT (Satisfiability Modulo Theories) -- расширение SAT, которое позволяет решать уравнения не только на уровне отдельных бит, но и с использованием более сложных конструкций, таких как битовые векторы или массивы. Именно формат SMT2 является стандартным входным языком для большинства современных солверов.

Движок верификации может использовать различные внешние программы-решатели. В нашем случае применяется встроенный движок `smtbmc` с внешним `z3` солвером. Подробнее про другие возможные движки и солверы можно прочитать в https://symbiyosys.readthedocs.io/en/latest/reference.html#engines-section[документации SymbiYosys].

NOTE: Все инструменты должны быть доступны после установки https://github.com/YosysHQ/oss-cad-suite-build[OSS CAD Suite].

== Операторы верификации

Для описания ограничений и проверок используются три оператора:

* `assume(выражение);` задает ограничения на входные сигналы. Солвер рассматривает только те сценарии, в которых данное выражение истинно. Без явных ограничений инструмент может подать на входы недопустимые спецификацией значения.
* `assert(выражение);` определяет целевое правило для проверки. Солвер ищет условия, нарушающие данное утверждение.
* `cover(выражение);` проверяет достижимость определенного состояния логики. Инструмент ищет хотя бы один набор значений сигналов, делающий выражение истинным.

Дополнительные инструменты SystemVerilog включают функции временного анализа (`$past` для чтения предыдущего состояния, `$stable` для проверки неизменности, `$rose`/`$fell` для фиксации фронтов) и атрибуты `(* anyseq \*)` или `(* anyconst *)` для создания несвязанных переменных, значения которых подбирает солвер. Примеры спецификаций описаны в https://symbiyosys.readthedocs.io/en/latest/verilog.html[документации SymbiYosys].

NOTE: Операторы верификации являются процедурными. Они должны находиться внутри процедурного контекста, например `always` или `initial`.

Для интеграции верификации в комбинационный модуль логика проверок изолируется макросом ``ifdef FORMAL`. Можно избежать изменения исходного модуля с помощью оператора `bind`{empty}footnote:[https://symbiyosys.readthedocs.io/en/latest/verific.html].

[source, verilog]
.src/02-combination-logic/formal-verification/adder_1_bit_fv.sv
----
include::example$adder_1_bit_fv.sv[]
----
<1> Логика исходного модуля-сумматора.
<2> Команда солверу убедиться в том, что данное условие выполняется всегда.
<3> Команда солверу вывести набор значений, когда выполняется данное условие.

== Настройка конфигурации

Управление процессом SymbiYosys происходит через конфигурационный файл `.sby`. Файл разбит на https://symbiyosys.readthedocs.io/en/latest/reference.html[секции]:

* `[options]`: режим работы и параметры анализа;
* `[engines]`: используемые движки и солверы с опциями;
* `[script]` : команды `Yosys` для чтения и подготовки топ-модуля;
* `[files]`  : исходные файлы модулей.

Секция `[options]` поддерживает три основных режима работы:

* `bmc` (Bounded Model Checking) проверяет выполнение `assert` от начального состояния схемы на фиксированную глубину шагов. Для комбинационной логики устанавливается `depth 1`.
* `cover` использует тот же алгоритм BMC, но переключает фокус солвера на поиск цепочки сигналов, удовлетворяющей условиям операторов `cover`. В данном режиме получить статус `FAIL` возможно в двух случаях: не найдена цепочка/набор сигналов, либо для достижения целевого состояния солверу придется нарушить любой из заданных `assert`.
* `prove` выполняет проверку BMC, а затем пытается построить неограниченное доказательство методом математической индукции (k-induction). Если режим завершается успешно, схема гарантированно работает корректно на любом временном интервале.

[source, ini]
.src/02-combination-logic/formal-verification/adder_1_bit.sby
----
include::example$adder_1_bit.sby[]
----

== Получение результата

Запуск верификации выполняется командой:

[,console]
----
sby adder_1_bit.sby
----

Инструмент выдаст статус `PASS`, подтвердив выполнение `assert` для всех 8 входных комбинаций. Чтобы увидеть результат оператора `cover`, требуется изменить режим `bmc` на `cover`.

После запуска команды создается папка (по умолчанию с именем файла конфигурации), в которой SymbiYosys организует промежуточные файлы и результаты:

* `src/`: копии исходных файлов;
* `model/`: результаты трансформации кода в математическое представление;
* `engine_N/`: для каждого солвера, указанного в секции [engines], создается своя папка. В ней лежат результаты работы математического движка:
** `trace.vcd`: файл данных трассы. В режиме `bmc/prove` это контрпример, показывающий, как именно сломался assert. В режиме cover -- пример трассы, достигающей нужного состояния.
** `trace_induct.vcd` (только для `prove`): трасса нарушения свойства на шаге индукции.
** `trace_tb.v`: Verilog-тестбенч, который можно запустить отдельно.
** `trace.smtc`: математическое описание трассы.
* Остальные файлы содержат логи и исходную конфигурацию.

Предположим, мы допустим опечатку при написании сумматора:

[source, verilog]
----
assign c_out = (a & b) | (c_in | (a ^ b));
----

При повторном запуске `sby -f adder_1_bit.sby` солвер Z3 найдет ситуацию, опровергающую `assert` условие. Процесс завершится со статусом `FAIL` и создадутся файлы с трассой. Так как для комбинационной логики используется `depth 1`, то для просмотра контрпримера достаточно файла `trace.smtc`:

----
initial

state 0
assume (= [a] false)
assume (= [b] true)
assume (= [c_in] false)
----

Для более сложных случаев можно воспользоваться утилитой GTKWave:

[,console]
----
gtkwave adder_1_bit/engine_0/trace.vcd
----

В интерфейсе программы необходимо выполнить следующие действия:

1. В панели `Signal Search Tree`/`SST` развернуть дерево и выбрать модуль `adder_1_bit_fv`.
2. В окне сигналов выделить интересующие переменные.
3. Добавить их на рабочую область нажатием кнопки `Insert` или двойным кликом.

С примерами верификации для последовательной логики можно ознакомиться по ссылкам {empty}footnote:[https://formal.org/abv/module/1]{empty}footnote:[https://zipcpu.com/formal/2018/05/31/clkswitch.html]. Для углубленного изучения можно почитать блоги https://zipcpu.com[zipcpu] или даже https://zipcpu.com/tutorial/formal.html[курс].
