= Тестбенч и CI

Итак, мы xref:index.adoc[написали] простой сумматор и посмотрели, что он выводит что-то адекватное. Такой способ тестирования, конечно, никуда не годится. В более привычных языках программирования принято писать unit-тесты, тестбенч{empty}footnote:[https://www.chipverify.com/verilog/verilog-testbench] нужен в том числе для этого.

Разберём простейший тестбенч:
[source, verilog]
.src/02-combination-logic/testbenches/adder_1_bit_tb.sv
----
include::example$adder_1_bit_tb.sv[]
----
<1> Задаём входные данные в виде векторов, которые будем считывать побитно. Примечателен формат целых чисел: `<количество знаков>'<система счисления><знак1>...<знакN>`, в данном случае у нас 8-ми битные числа.
<2> Задаём ожидаемые результаты.
<3> Задаём цикл, тут всё, как у людей, настоящий си-подобный синтаксис.
<4> Считываем очередной бит входных данных.
<5> Проверяем, что актуальные результаты совпали с ожидаемыми, для этого используем `assert`{empty}footnote:[https://www.doulos.com/knowhow/systemverilog/systemverilog-tutorials/systemverilog-assertions-tutorial/].
<6> Если условие не выполнено, то падаем с ошибкой.

Это больше похоже на привычные нам тесты. И раз они есть, значит можно сделать любимый всеми программистами CI.
Во-первых, раз мы xref:01-basic-environment:ide-setup.adoc[настроили] линтер, то нужно запускать его автоматически.
Как это сделали мы, можно посмотреть{empty}footnote:[Репозиторий курса: https://github.com/Lamagraph/intro-to-fpga-with-clash] в файле `.github/workflows/lint.yaml`.
Во-вторых, запускать всё вручную неприятно, напишем Makefile, на который можно посмотреть в файле `src/02-adder/Makefile`.
Ну и в конце запустим всё это в CI. Опять, подробности можно посмотреть здесь: `.github/workflows/tests.yaml`.
Готово, код проверяется, проект собирается, тесты запускаются.

Последовательность действий ничем не отличается от того, к чему Вы привыкли при работе с другими инструментами, что не может не радовать.
Настоятельно рекомендуем посмотреть на все приведённые выше файлы и реализовать что-то подобное для своих проектов.

IMPORTANT: Обязательно пройдите xref:exercises.adoc[упражнения].
