= 11. Введение в Clash

== Мотивация

https://clash-lang.org/[Clash] -- это тоже HDL, однако он опирается на идеи функционального программирования, написан на Haskell и использует его же в качестве основы.
Это даёт несколько преимуществ: развитая инфраструктура, более хорошая документация, и, главное, возможность относительно легко создавать высокоуровневые абстракции.
В общем-то по большей части для этого он нам и будет нужен: в конечном итоге мы всё равно будем синтезировать полученные программы в SystemVerilog (но это не единственная опция, можно и в VHDL, например).

== Начало работы

В xref:10-haskell:index.adoc[прошлый раз] мы уже установили Haskell.
Так что https://clash-lang.org/install/linux/[поставить Clash] не составит труда (выбираем опцию B).
Там будет базовый пример, который мы не будем удалять.
Проверить, что всё работает можно, например, запустив тесты.
[, console]
----
$ stack test
----

NOTE: Хоть Clash и является просто ещё одним пакетом, он перекрывает стандартную Prelude своей, надо иметь это в виду.

== Опять сумматор

Знакомство с SystemVerilog мы начинали с xref:02-combination-logic:index.adoc[реализации полного сумматора], здесь поступим так же.
С точки зрения логики тут нет ничего незнакомого, но дьявол, как водится, кроется в деталях.

[, haskell]
.src/11-clash/clash-examples/src/FullAdder.hs
----
include::example$FullAdder.hs[]
----
<1> Модуль для создания аннотаций верхнеуровевой функции.
<2> Как и было сказано, Prelude переписывается самим Clash{empty}footnote:[https://hackage.haskell.org/package/clash-prelude-1.8.1], а стандартная по умолчанию не импортирована.
<3> Сигнатура нашего сумматора.
https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Sized-BitVector.html#t:Bit[`Bit`] именно Clash-вский тип, можно было бы сделать и на `Bool`-ах.
<4> Верхнеуровневая функция, замена `main`.
Именно то, что написано здесь, будет в итоге синтезироваться в SystemVerilog.
<5> Можно задать имена аргументам в сигнатуре функции, это сделано, чтобы сгенерированный `.sv` файл было легче читать{empty}footnote:[https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-NamedTypes.html].
<6> Заклинание, чтобы проделанное в 5 работало{empty}footnote:[https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Annotations-TH.html#v:makeTopEntity].

[TIP]
====
Попробуйте сгенерировать .sv файлик.
Это можно сделать так (из директории `src/11-clash/clash-examples`).
[,console]
----
$ stack run clash -- FullAdder --systemverilog
----
Убедитесь, что он похож на то, что писали мы.
====

Самое приятное здесь то, что мы отделили функциональную часть от той, которая по итогу пойдёт на синтез.
Так что можно написать тесты к функции `fullAdder`, и если они проходятся, то с большой вероятностью сгенерированный модуль будет работать также исправно.

[,haskell]
.src/11-clash/clash-examples/tests/Tests/FullAdder.hs
----
include::example$FullAdderTest.hs[]
----
<1> К сожалению, Clash-овые типы не могут генерироваться `Hedgehog.Gen`, поэтому приходится брать `Bool`.
<2> На наше счастье, `Bool` легко переделать в `Bit`{empty}footnote:[https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Class-BitPack-Internal.html#v:boolToBit].
<3> Мы можем привычно складывать битвектора, но функция `boolToBV` требует, чтобы мы уточнили итоговый тип (напомню, что в Clash в типе `BitVector` зашита его длинна).
Здесь можно было бы уточнить тип сразу после применения функции `boolToBV` (это выглядело бы так `C.boolToBV a +::+ BitVector 2`), дальше haskell сам бы догадался, какой тип у остальных применений, потому что сложение не меняет его.
Это распространённая ситуация: иногда, если у вас что-то не работает, хотя по логике должно, то стоит подумать о том, чтобы явно указать тип (это можно, как видно, делать в любом месте, хоть после каждого применения функции).
<4> Тут и ниже -- стандартная магия, чтобы всё заработало.

[IMPORTANT]
====
Тут несколько иначе настроена инфраструктура для тестов, так что важно.

. Добавить модуль в `src/11-clash/clash-examples/clash-examples.cabal` в `library` и `test-suite`.
. Добавить нужную функцию в `src/11-clash/clash-examples/tests/unittests.hs`.
====

== Многобитный сумматор

Не отходя далеко, давайте напишем многобитный сумматор через реализованную функцию.

[, haskell]
----
include::example$FullAdderMultibits.hs[]
----
<1> Задаём ограничение типа через класс{empty}footnote:[https://hackage.haskell.org/package/base-4.14.3.0/docs/GHC-TypeNats.html#t:KnownNat].
Очень-очень часто встречается, оно позволяет нам в некотором смысле параметризовать функции, как мы делали это в SystemVerilog.
Однако этот механизм несколько более хитрый и мощный.
<2> Берём не https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Sized-BitVector.html#t:BitVector[`BitVector`], а просто https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Sized-Vector.html#t:Vec[`Vec`] потому что с ним можно сделать сильно больше вещей, из которых нам нужна будет свёртка (`foldr`).
<3> Делаем вектор из одних нулей.
Здесь Haskell сам догадается какой длинны он должен быть, именно для этого написаны 2 первые строчки подключения расширений{empty}footnote:[https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/partial_type_signatures.html].
Здесь пример вырожденный, но такие вещи достаточно распространены и в более сложных случаях.
<4> Свёртка, но не простая, а как раз на векторах{empty}footnote:[https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Prelude.html#v:foldr], Ещё одно проявление спрятанной стандартной Prelude.
Работает аналогично.
<5> Вектор фиксированной длинны, так что оператор вставки в начало "вытесняет" последний бит{empty}footnote:[https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Sized-Vector.html#v:-43--62--62-].

IMPORTANT: Обязательно порешайте xref:exercises.adoc[упражнения].
